"""Agregar columnas x e y a la tabla Nodo

Revision ID: 2346568e48e9
Revises: 6bdca6714b8b
Create Date: 2025-03-22 13:14:17.586206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2346568e48e9'
down_revision = '6bdca6714b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo', schema=None) as batch_op:
        batch_op.drop_column('y')
        batch_op.drop_column('x')

    # ### end Alembic commands ###
