"""Agregar coordenadas de las líneas a la tabla Nodo

Revision ID: 686bef8b7a81
Revises: 690d3c754f79
Create Date: 2025-03-22 14:47:59.014138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686bef8b7a81'
down_revision = '690d3c754f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('x2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['nodo.id'], name='relacion_source_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['nodo.id'], name='relacion_target_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='relacion_pkey')
    )
    # ### end Alembic commands ###
