"""Crear tabla relaciones

Revision ID: 690d3c754f79
Revises: 2346568e48e9
Create Date: 2025-03-22 13:43:49.745948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690d3c754f79'
down_revision = '2346568e48e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['nodo.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['nodo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('relaciones')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('x2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['nodo.id'], name='relaciones_source_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['nodo.id'], name='relaciones_target_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='relaciones_pkey')
    )
    op.drop_table('relacion')
    
    # ### end Alembic commands ###
