"""Agregar columna color a Nodo

Revision ID: 6bdca6714b8b
Revises: 817f99e0a232
Create Date: 2025-03-22 12:59:59.247635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdca6714b8b'
down_revision = '817f99e0a232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodos')
    with op.batch_alter_table('nodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint('nodo_parent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nodo', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nodo_parent_id_fkey', 'nodo', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('color')

    op.create_table('nodos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('forma', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nodos.id'], name='nodos_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='nodos_pkey')
    )
    # ### end Alembic commands ###
