"""Agregar columnas x1, y1, x2, y2 a la tabla nodo

Revision ID: d8e9aff59b8d
Revises: 686bef8b7a81
Create Date: 2025-03-22 14:59:29.160340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e9aff59b8d'
down_revision = '686bef8b7a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('x2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y2', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo', schema=None) as batch_op:
        batch_op.drop_column('y2')
        batch_op.drop_column('x2')
        batch_op.drop_column('y1')
        batch_op.drop_column('x1')

    # ### end Alembic commands ###
